// add register
export const SEND_REGISTER_REQUEST = "SEND_REGISTER_REQUEST";
export const SEND_REGISTER_SUCCESS = "SEND_REGISTER_SUCCESS";
export const SEND_REGISTER_FAILED = "SEND_REGISTER_FAILED";

//login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT";

//checkPhoneNumber
export const CHECK_PHONE_REQUEST = "CHECK_PHONE_REQUEST";
export const CHECK_PHONE_FAILED = "CHECK_PHONE_FAILED";
export const CHECK_PHONE_SUCCESS = "CHECK_PHONE_SUCCESS";

//requestCode
export const REQUEST_CODE_REQUEST = "GET_CODE_REQUEST";
export const REQUEST_CODE_FAILED = "GET_CODE_FAILED";
export const REQUEST_CODE_SUCCESS = "GET_CODE_SUCCESS";

//requestListDoctor
export const GET_LIST_DOCTOR_REQUEST = "GET_LIST_DOCTOR_REQUEST";
export const GET_LIST_DOCTOR_FAILED = "GET_LIST_DOCTOR_FAILED";
export const GET_LIST_DOCTOR_SUCCESS = "GET_LIST_DOCTOR_SUCCESS";
//search doctor
export const SEARCH_DOCTOR_REQUEST = "SEARCH_DOCTOR_REQUEST";
export const SEARCH_DOCTOR_FAILED = "SEARCH_DOCTOR_FAILED";
export const SEARCH_DOCTOR_SUCCESS = "SEARCH_DOCTOR_SUCCESS";
//confirmCode
export const CONFIRM_CODE_REQUEST = "CONFIRM_CODE_REQUEST";
export const CONFIRM_CODE_FAILED = "CONFIRM_CODE_FAILED";
export const CONFIRM_CODE_SUCCESS = "CONFIRM_CODE_SUCCESS";

//resetPass
export const RESET_PASS_REQUEST = "RESET_PASS_REQUEST";
export const RESET_PASS_FAILED = "RESET_PASS_FAILED";
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";

// SUBJECT
export const SUBJECT_REQUEST = "SUBJECT_REQUEST";
export const SUBJECT_FAILED = "SUBJECT_FAILED";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
//GET CONTACT
export const GET_CONTACT_REQUEST = "GET_CONTACT";
export const GET_CONTACT_FAILED = "GET_CONTACT_FAILED";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";

// finder
export const FINDER_REQUEST = "FINDER_REQUEST";
export const FINDER_FAILED = "FINDER_FAILED";
export const FINDER_SUCCESS = "FINDER_SUCCESS";

// add
export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_FAILED = "ADD_FAILED";
export const ADD_SUCCESS = "ADD_SUCCESS";

// CHAT
export const CHAT_HISTORIES_REQUEST = "CHAT_HISTORIES_API";
export const CHAT_HISTORIES_FAILED = "CHAT_HISTORIES_FAILED";
export const CHAT_HISTORIES_SUCCESS = "CHAT_HISTORIES_SUCCESS";

export const CHAT_HISTORIES_GROUP_REQUEST = "CHAT_HISTORIES_GROUP_API";
export const CHAT_HISTORIES_GROUP_FAILED = "CHAT_HISTORIES_GROUP_FAILED";
export const CHAT_HISTORIES_GROUP_SUCCESS = "CHAT_HISTORIES_GROUP_SUCCESS";

export const SAVE_CHAT_MESSAGE = "SAVE_CHAT_MESSAGE";

// CHAT ROOM CURRENT
export const CHAT_ROOM_CURRENT_REQUEST = "CHAT_ROOM_CURRENT_REQUEST";
export const CHAT_ROOM_CURRENT_FAILED = "CHAT_ROOM_CURRENT_FAILED";
export const CHAT_ROOM_CURRENT_SUCCESS = "CHAT_ROOM_CURRENT_SUCCESS";
export const CHAT_ROOM_CURRENT_REMOVE = "CHAT_ROOM_CURRENT_REMOVE";

// Post Contact
export const SEND_CONTACT_REQUEST = "SEND_CONTACT_REQUEST";
export const SEND_CONTACT_FAILED = "SEND_CONTACT_FAILED";
export const SEND_CONTACT_SUCCESS = "SEND_CONTACT_SUCCESS";

// delete Contact
export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const EDIT_CONTACT_LOCAL = "EDIT_CONTACT_LOCAL";
//ALERT
export const ALERT_CLOSE = "ALERT_CLOSE";
export const ALERT_OPEN = "ALERT_OPEN";

//DRAWER
export const DRAWER_CLOSE = "DRAWER_CLOSE";
export const DRAWER_OPEN = "DRAWER_OPEN";
export const ON_NAVIGATE = "ON_NAVIGATE";
export const NAVIGATE_TO = "NAVIGATE_TO";

// LIKE
export const SEND_LIKE_REQUEST = "SEND_LIKE_REQUEST";
export const SEND_LIKE_FAILED = "SEND_LIKE_FAILED";
export const SEND_LIKE_SUCCESS = "SEND_LIKE_SUCCESS";

// avatar
export const AVATAR_REQUEST = "AVATAR_REQUEST";
export const AVATAR_SUCCESS = "AVATAR_SUCCESS";
export const AVATAR_FAILED = "AVATAR_FAILED";

// call
export const CALL_HISTORY_REQUEST = "CALL_HISTORY";
export const CALL_HISTORY_SUCCESS = "CALL_HISTORY_SUCCESS";
export const CALL_HISTORY_FAILED = "CALL_HISTORY_FAILED";

// details
export const CALL_DETAILS_REQUEST = "CALL_DETAILS";
export const CALL_DETAILS_SUCCESS = "CALL_DETAILS_SUCCESS";
export const CALL_DETAILS_FAILED = "CALL_DETAILS_FAILED";
// list chat
export const GET_LIST_CHAT_REQUEST = "GET_LIST_CHAT";
export const GET_LIST_CHAT_SUCCESS = "GET_LIST_CHAT_SUCCESS";
export const GET_LIST_CHAT_FAILED = "GET_LIST_CHAT_FAILED";
// create groupChat
export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAILED = "CREATE_GROUP_CHAT_FAILED";
// delete
export const CALL_DELETE_REQUEST = "CALL_DELETE_REQUEST";
export const CALL_DELETE_SUCCESS = "CALL_DELETE_SUCCESS";
export const CALL_DELETE_FAILED = "CALL_DELETE_FAILED";

//FAVORITE
export const SEND_FAVORITE_REQUEST = "SEND_FAVORITE";
export const SEND_FAVORITE_SUCCESS = "SEND_FAVORITE_SUCCESS";
export const SEND_FAVORITE_FAILED = "SEND_FAVORITE_FAILED";

// sync contact
export const SYNC_CONTACT_REQUEST = "SYNC_CONTACT_REQUEST";
export const SYNC_CONTACT_SUCCESS = "SYNC_CONTACT_SUCCESS";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
// Detail contact
export const DETAIL_CONTACT_REQUEST = "DETAIL_CONTACT_REQUEST";
export const DETAIL_CONTACT_FAILED = "DETAIL_CONTACT_FAILED";
export const DETAIL_CONTACT_SUCCESS = "DETAIL_CONTACT_SUCCESS";

// LOCAL NOTIFICATION
export const OPEN_LOCAL_NOTIFICATION = "OPEN_LOCAL_NOTIFICATION";
export const CLOSE_LOCAL_NOTIFICATION = "CLOSE_LOCAL_NOTIFICATION";
// export const REMOVE_CONTACT = "REMOVE_CONTACT";

// Profile
export const PROFILE_EDIT_REQUEST = "PROFILE_EDIT_REQUEST";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAILED = "PROFILE_EDIT_FAILED";

//topic
export const TOPIC_REQUEST = "TOPIC";
export const TOPIC_SUCCESS = "TOPIC_SUCCESS";
export const TOPIC_FAILED = "TOPIC_FAILED";

export const SPECIALIZE_REQUEST = "SPECIALIZE";
export const SPECIALIZE_SUCCESS = "SPECIALIZE_SUCCESS";
export const SPECIALIZE_FAILED = "SPECIALIZE_FAILED";

// positon
export const POSITION_REQUEST = "POSITION";
export const POSITION_SUCCESS = "POSITION_SUCCESS";
export const POSITION_FAILED = "POSITION_FAILED";

// school
export const SCHOOL_REQUEST = "SCHOOL";
export const SCHOOL_SUCCESS = "SCHOOL_SUCCESS";
export const SCHOOL_FAILED = "SCHOOL_FAILED";

/// search
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";

//search Map Teacher
export const GET_MAP_TEACHER_REQUEST = "GET_MAP_TEACHER";
export const GET_MAP_TEACHER_SUCCESS = "GET_MAP_TEACHER_SUCCESS";
export const GET_MAP_TEACHER_FAILED = "GET_MAP_TEACHER_FAILED";
//
export const TRANSACTION_REQUEST = "TRANSACTION";
export const TRANSACTION_FAILED = "TRANSACTION_FAILED";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FULL_REQUEST = "TRANSACTION_FULL";
export const TRANSACTION_FULL_FAILED = "TRANSACTION_FULL_FAILED";
export const TRANSACTION_FULL_SUCCESS = "TRANSACTION_FULL_SUCCESS";

// Lang
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

//setting
export const SWITCH_VIBRATION = "SWITCH_VIBRATION";
export const SWITCH_VIBRATION_CALL = "SWITCH_VIBRATION_CALL";
export const SWITCH_SOUND = "SWITCH_SOUND";
export const SWITCH_SOUND_CALL = "SWITCH_SOUND_CALL";
export const SWITCH_MESSAGE_NOTI = "SWITCH_MESSAGE_NOTI";
export const SWITCH_GROUP_NOTI = "SWITCH_GROUP_NOTI";
export const SWITCH_ONLINE_STATUS = "SWITCH_ONLINE_STATUS";

// get list teacher
export const GET_TEACHER_REQUEST = "GET_TEACHER";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAILED = "GET_TEACHER_FAILED";

//favorite get teacher

export const GET_FAVORITE_TEACHER_REQUEST = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_TEACHER_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_TEACHER_FAILED = "GET_FAVORITE_FAILED";

//favorite post

export const POST_FAVORITE_TEACHER_REQUEST = "POST_FAVORITE_TEACHER_REQUEST";
export const POST_FAVORITE_TEACHER_SUCCESS = "POST_FAVORITE_TEACHER_SUCCESS";
export const POST_FAVORITE_TEACHER_FAILED = "POST_FAVORITE_TEACHER_FAILED";

//favorite detele

export const DELETE_FAVORITE_TEACHER_REQUEST = "DELETE_FAVORITE_TEACHER_REQUEST";
export const DELETE_FAVORITE_TEACHER_SUCCESS = "DELETE_FAVORITE_TEACHER_SUCCESS";
export const DELETE_FAVORITE_TEACHER_FAILED = "DELETE_FAVORITE_TEACHER_FAILED";

// get favorite teacher

export const GET_LIST_FAVORITE_TEACHER_REQUEST = "GET_LIST_FAVORITE_TEACHER";
export const GET_LIST_FAVORITE_TEACHER_SUCCESS = "GET_LIST_FAVORITE_TEACHER_SUCCESS";
export const GET_LIST_FAVORITE_TEACHER_FAILED = "GET_LIST_FAVORITE_TEACHER_FAILED";

//TODO: NEW

export const GET_LIST_TAG_REQUEST = "GET_LIST_TAG";
export const GET_LIST_TAG_SUCCESS = "GET_LIST_TAG_SUCCESS";
export const GET_LIST_TAG_FAILED = "GET_LIST_TAG_FAILED";

// EVENT
export const GET_EVENT_REQUEST = "GET_EVENT";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILED = "GET_EVENT_FAILED";
export const GET_EVENT_UNCOMFIRMATION_SUCCESS = "GET_EVENT_UNCOMFIRMATION_SUCCESS";
export const GET_EVENT_ACTIVE_SUCCESS = "GET_EVENT_ACTIVE_SUCCESS";

export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";

// Create even
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";

export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";
//get event
export const GET_EVENT_DETAIL_REQUEST = "GET_EVENT_DETAIL_REQUEST";
export const GET_EVENT_DETAIL_SUCCESS = "GET_EVENT_DETAIL_SUCCESS";
export const GET_EVENT_DETAIL_FAILED = "GET_EVENT_DETAIL_FAILED";
// active
export const RATING_EVENT_SUCCESS = "RATING_EVENT_SUCCESS";
export const COMPLETE_EVENT_SUCCESS = "COMPLETE_EVENT_SUCCESS";
export const ACTIVE_EVENT_SUCCESS = "ACTIVE_EVENT_SUCCESS";
export const CANCEL_EVENT_SUCCESS = "CANCEL_EVENT_SUCCESS";

// METTING_AGENDA
export const GET_METTING_AGENDA_REQUEST = "GET_METTING_AGENDA";
export const GET_METTING_AGENDA_SUCCESS = "GET_METTING_AGENDA_SUCCESS";
export const GET_METTING_AGENDA_FAILED = "GET_METTING_AGENDA_FAILED";
// get
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const REMOVE_USER = "REMOVE_USER";
export const GET_PASSWORD = "GET_PASSWORD";

//NEWS
export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_FAILED = "GET_NEWS_FAILED";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";

//NEWS DETAIL
export const GET_NEWS_DETAIL_REQUEST = "GET_NEWS_DETAIL_REQUEST";
export const GET_NEWS_DETAIL_FAILED = "GET_NEWS_DETAIL_FAILED";
export const GET_NEWS_DETAIL_SUCCESS = "GET_NEWS_DETAIL_SUCCESS";
// FOR GOT
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
// SAMPLE CHAT
export const SAMPLE_CHAT_REQUEST = "SAMPLE_CHAT_REQUEST";
export const GET_SAMPLE_CHAT_FAILED = "GET_SAMPLE_CHAT_FAILED";
export const GET_SAMPLE_CHAT_SUCCESS = "GET_SAMPLE_CHAT_SUCCESS";
// CREATE
export const CREATE_SAMPLE_CHAT_REQUEST = "CREATE_SAMPLE_CHAT_REQUEST";
export const CREATE_SAMPLE_CHAT_FAILED = "CREATE_SAMPLE_CHAT_FAILED";
export const CREATE_SAMPLE_CHAT_SUCCESS = "CREATE_SAMPLE_CHAT_SUCCESS";
